name: Job Automation

on:
  workflow_dispatch:

jobs:
  run-job-fetcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run job fetcher
        run: python src/job_fetcher.py
